config/routes.rb
Rails.application.routes.draw do
  
  resources :atm_maches 
    devise_for :users, controllers: {sessions: 'users/sessions'}
    resources :accounts,only: [:new,]
    resources :transactions
    resources :user_infos
    root 'atm_maches#index'
      
    resources :accounts do
      member do
        get :transaction_list
        get :select_transaction
        get :new_deposit
        post :create_deposit
        get :new_withdrawal
        post :create_withdrawal
      end
    end
  
end

app/models/atm_mach.rb
class AtmMach < ActiveRecord::Base
  has_many :transactions
  def show
    session[:atm_no] = @atm_machine.id
  end
  def sort
    scope :sort, -> { order(id: :asc) }
  end
end

app/controllers/atm_maches_controller.rb
class AtmMachesController < ApplicationController
  before_action :set_atm_mach, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]
  # GET /atm_maches
  # GET /atm_maches.json
  def index
    @atm_maches = AtmMach.all
  end

  # GET /atm_maches/1
  # GET /atm_maches/1.json
  def show
     session[:atm_no] = @atm_mach.id

  end

  # GET /atm_maches/new
  def new
    @atm_mach = AtmMach.new
  end

  # GET /atm_maches/1/edit
  def edit
  end

  # POST /atm_maches
  # POST /atm_maches.json
  def create
    @atm_mach = AtmMach.new(atm_mach_params)

    respond_to do |format|
      if @atm_mach.save
        format.html { redirect_to @atm_mach, notice: 'Atm mach was successfully created.' }
        format.json { render :show, status: :created, location: @atm_mach }
      else
        format.html { render :new }
        format.json { render json: @atm_mach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atm_maches/1
  # PATCH/PUT /atm_maches/1.json
  def update
    respond_to do |format|
      if @atm_mach.update(atm_mach_params)
        format.html { redirect_to @atm_mach, notice: 'Atm mach was successfully updated.' }
        format.json { render :show, status: :ok, location: @atm_mach }
      else
        format.html { render :edit }
        format.json { render json: @atm_mach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atm_maches/1
  # DELETE /atm_maches/1.json
  def destroy
    @atm_mach.destroy
    respond_to do |format|
      format.html { redirect_to atm_maches_url, notice: 'Atm mach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_atm_mach
      @atm_mach = AtmMach.find(params[:id])
    end

    def atm_mach_params
      params.require(:atm_mach).permit(:name, :state, :city, :zip_code, :street)
    end
end

app/helpers/atm_maches_helper.rb
module AtmMachesHelper
end

app/views/atm_maches/_form.html.erb
<%= form_for(@atm_mach) do |f| %>
  <% if @atm_mach.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atm_mach.errors.count, "error") %> prohibited this atm_mach from being saved:</h2>

      <ul>
      <% @atm_mach.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.text_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :street %><br>
    <%= f.text_field :street %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atm_maches/edit.html.erb
<h1>Editing Atm Mach</h1>

<%= render 'form' %>

<%= link_to 'Show', @atm_mach %> |
<%= link_to 'Back', atm_maches_path %>

app/views/atm_maches/index.html.erb
<hr>
<center><h2> ATMS Available Locations </h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>ATM #</th>
      <th>Name</th>
      <th>State</th>
      <th>City</th>
      <th>Zip code</th>
      <th>Street</th>
      <th>ATM Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @atm_maches.each do |atm_mach| %>
      <tr>
      <td><%= atm_mach.id %></td>
      <td><%= atm_mach.name %></td>
      <td><%= atm_mach.state %></td>
      <td><%= atm_mach.city %></td>
      <td><%= atm_mach.zip_code %></td>
      <td><%= atm_mach.street %></td>
      <td><%= link_to 'Start' , atm_mach , class:"btn btn-info"%></td></center
     
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/atm_maches/new.html.erb
<h1>New Atm Mach</h1>

<%= render 'form' %>

<%= link_to 'Back', atm_maches_path %>

app/views/atm_maches/show.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-2 ">
    <div class="col-md-9 col-md-offset-2 ">
      <h4> 
        <br><br><br><br>
        <center><strong>ATM Name:</strong>
        <%= @atm_mach.name %>
      </h4>
      <h4>
        <strong>ATM Address</strong>
        <%= @atm_mach.street %>
        <%= @atm_mach.city %>
        <%= @atm_mach.state %>
        <%= @atm_mach.zip_code %>
      </h4><hr></center>
      <%if current_user.account.present? %>
        <center><h3>Avalable Balance : 
        <strong><%=number_to_currency(current_user.account.balance.to_f)%> </strong></h3></center>
      <%else%>
        <center><h3><strong class="label label-danger text-uppercase "> <%= p "NO Account Associated This Email " %></strong></h3></center>
      <%end%><hr>
    </div>
  </div>
</div>
<div class="row"> 
  <div class="col-md-8 col-md-offset-3">
    <% if current_user.user_info.present? %>
       <center><p><%=link_to 'transactions',  transaction_list_account_path(current_user.account ),class:"btn btn-info btn-lg"%> &nbsp;
      <%=link_to 'Withdrawal ', new_withdrawal_account_path(current_user.account ),class:"btn btn-danger btn-lg"%> &nbsp;
      <%=link_to 'Add Deposit',  new_deposit_account_path(current_user.account),class:"btn btn-success btn-lg"%> &nbsp;
       <%= link_to 'Information',edit_user_info_path(current_user.user_info.id,atm_no: @atm_mach.id),class:"btn btn-info btn-lg"%> &nbsp;</p></center>
        <center><%= link_to 'Avalable ATMS', atm_maches_path ,class:"btn btn-info btn-lg" %></center>
    <%else%> 
      <div class="row">
      <center><%= link_to 'Create New Account ',new_user_info_path(atm_no: @atm_mach.id ),class:" col-md-4 col-md-offset-2  btn btn-info btn-lg" %></center>
      </div>
    <%end%>
  </div>
</div>        

 