config/routes.rb
Rails.application.routes.draw do
  
  resources :atm_maches 
    devise_for :users, controllers: {sessions: 'users/sessions'}
    resources :accounts,only: [:new,]
    resources :transactions
    resources :user_infos
    root 'atm_maches#index'
      
    resources :accounts do
      member do
        get :transaction_list
        get :select_transaction
        get :new_deposit
        post :create_deposit
        get :new_withdrawal
        post :create_withdrawal
      end
    end
  
end

app/models/user_info.rb
class UserInfo < ActiveRecord::Base
  belongs_to :user
  validates :first_name,:last_name,:email,:city,:state,:street,:zip_code, :presence => true      
  validates_format_of :phone,:with => /\(?[0-9]{3}\)?-[0-9]{3}-[0-9]{4}/,:message => "- Phone numbers must be in xxx-xxx-xxxx format."
  validates :first_name, uniqueness: { scope: [:last_name,:email] , message: "or last name should be unique" },case_sensitive: false
  after_create :create_account

  private
    def create_account
      Account.create(user_id: user_id , balance: 0.0) 
    end

end

app/controllers/user_infos_controller.rb
class UserInfosController < ApplicationController
  before_action :set_user_info, only: [:show, :edit, :update, :destroy]

  # GET /user_infos
  # GET /user_infos.json
  def index
    @user_infos = UserInfo.all
  end

  # GET /user_infos/1
  # GET /user_infos/1.json
  def show
  end

  # GET /user_infos/new
  def new
      @user_info = UserInfo.new
      session[:atm_no] = params[:atm_no] 
  end

  # GET /user_infos/1/edit
  def edit
    session[:atm_no] = params[:atm_no] 
  end

  # POST /user_infos
  # POST /user_infos.json
  def create
    
  @user_info = UserInfo.new(user_info_params)
  @atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_info.save
        format.html { redirect_to atm_mach_path(session[:atm_no])}
        format.json { render :show, status: :created, location: @user_info }
      else
        format.html { render :new }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_infos/1
  # PATCH/PUT /user_infos/1.json
  def update
    @atm_no = params[:atm_no] 
    respond_to do |format|
      if @user_info.update(user_info_params)
        format.html { redirect_to atm_mach_path(session[:atm_no])}
        format.json { render :show, status: :ok, location: @user_info }
      else
        format.html { render :edit }
        format.json { render json: @user_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_infos/1
  # DELETE /user_infos/1.json
  def destroy
    @user_info.destroy
    respond_to do |format|
      format.html { redirect_to user_infos_url, notice: 'User info destroyed successfully ' }
      format.json { head :no_content }
    end
  end

  private
    def set_user_info
      @user_info = UserInfo.find(params[:id])
    end

    def user_info_params
      params.require(:user_info).permit(:first_name, :last_name, :email, :phone, :city, :state, :zip_code, :street,:user_id,:account)
    end
end

app/helpers/user_infos_helper.rb
module UserInfosHelper
end

app/views/user_infos/_form.html.erb
<%= form_for @user_info, html: { class:'form_horizontal' } do |f| %>
    <% if @user_info.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user_info.errors.count, "error") %> prohibited this user_info from being saved:</h2>
  
        <ul>
        <% @user_info.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    

<div class="col-md-9 col-md-offset-1">

    <table class="table table-striped containe   text-left   " >
              
              <tr>
                <td>
                  <div class="control-group">
                    <%= f.label :first_name %>
                    <%= f.text_field :first_name ,class:"form-control"%>
                    </div>
                  </div>
                </td>        
               
                  
                <td>
                  <div class="control-group">
                    <%= f.label :last_name, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :last_name ,class:"form-control"%>
                     </div>
                  </div>
                </td>
              </tr>         
              
              <tr>
                <td>
                  <div class="control-group">
                    <%= f.label :email, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :email ,class:"form-control"%>
                     </div>
                  </div>
                </td>
                
                <td>         
                  <div class="control-group">
                    <%= f.label :phone, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :phone,class:"form-control" %>
                     </div>
                  </div>
                </td>
              </tr>
              
              <tr>
                <td>         
                  <div class="control-group">
                    <%= f.label :city, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :city,class:"form-control" %>
                     </div>
                  </div>
                </td>
                
                <td>           
                  <div class="control-group">
                    <%= f.label :state, class: 'control-label'%>
                    <dev class="controls">
                    <%= f.text_field :state,class:"form-control" %> 
                    </div>
                  </div>
                </td>
              </tr>
              
              <tr>
                <td>         
                  <div class="control-group">
                    <%= f.label :zip_code, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :zip_code ,class:"form-control"%>
                     </div>
                  </div>
                </td>
                
                <td>        
                  <div class="control-group">
                    <%= f.label :street, class: 'control-label' %>
                    <dev class="controls">
                    <%= f.text_field :street ,class:"form-control"%>
                     </div>
                  </div>
                </td>
              </tr>
              
              
              
              <tr>
                <td>    
                  <div class="control-group">
                    <%= f.submit 'Update', class:"btn btn-default  "%>
                    <dev class="controls">
                     </div>
                    </div>
                </td>
              </tr>

    </table>
</div>

          <div class="field">
              <%=f.hidden_field :user_id, value: current_user.id %>
          </div>

<% end %>

app/views/user_infos/edit.html.erb
<center><br><h3>Update Information</h3><br></center>

<%= render 'form' %>

app/views/user_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Infos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <th>State</th>
      <th>Zip code</th>
      <th>Street</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_infos.each do |user_info| %>
      <tr>
        <td><%= user_info.first_name %></td>
        <td><%= user_info.last_name %></td>
        <td><%= user_info.email %></td>
        <td><%= user_info.phone %></td>
        <td><%= user_info.city %></td>
        <td><%= user_info.state %></td>
        <td><%= user_info.zip_code %></td>
        <td><%= user_info.street %></td>
        <td><%= user_info.user_id %></td>
        <td><%= link_to 'Show', user_info %></td>
        <td><%= link_to 'Edit', edit_user_info_path(user_info) %></td>
        <td><%= link_to 'Destroy', user_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User info', new_user_info_path %>

app/views/user_infos/new.html.erb
<center></br><h3>New  Account User Informations</h3></center>

<%= render 'form' %>
<br><br>

app/views/user_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user_info.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user_info.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user_info.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user_info.phone %>
</p>

<p>
  <strong>City:</strong>
  <%= @user_info.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user_info.state %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @user_info.zip_code %>
</p>

<p>
  <strong>Street:</strong>
  <%= @user_info.street %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_info.user_id %>
</p>

<%= link_to 'Edit', edit_user_info_path(@user_info) %> |
<%= link_to 'Back', user_infos_path %>